package asyetuntitled.common.item;

import asyetuntitled.AsYetUntitled;
import asyetuntitled.common.block.BlocksRegistry;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class ItemsRegistry 
{
	private static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, AsYetUntitled.MODID);
	
	public static final CreativeModeTab ITEM_GROUP = new CreativeModeTab(AsYetUntitled.MODID) {
	        @Override
	        public ItemStack makeIcon() {
	            return new ItemStack(ItemsRegistry.BLANK_SLOT.get());
	        }
	};
	public static final Item.Properties ITEM_PROPERTIES = new Item.Properties().tab(ITEM_GROUP);
	
	public static final RegistryObject<Item> BLANK_SLOT = ITEMS.register("blank_slot", () -> new ItemBlankSlot(new Item.Properties().tab(ITEM_GROUP).stacksTo(1)));
	public static final RegistryObject<Item> BACKPACK_BASE = ITEMS.register("backpack_base", () -> new ItemBackpack(new Item.Properties().tab(ITEM_GROUP).stacksTo(1), 9));
	public static final RegistryObject<Item> LIVING_CHEST_STAFF = ITEMS.register("living_chest_staff", () -> new ItemStaff(new Item.Properties().tab(ITEM_GROUP).stacksTo(1)));
	
	public static final RegistryObject<Item> BACKPACK_MAIN = ITEMS.register("backpack/main", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> BACKPACK_MAIN_BUTTONS = ITEMS.register("backpack/main_buttons", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> BACKPACK_TOP = ITEMS.register("backpack/top", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> BACKPACK_TOP_BUTTONS = ITEMS.register("backpack/top_buttons", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> BACKPACK_FRONT = ITEMS.register("backpack/front", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> BACKPACK_FRONT_BUTTONS = ITEMS.register("backpack/front_buttons", () -> new Item(new Item.Properties()));
	
	public static final RegistryObject<Item> DUMMY_RUNE = ITEMS.register("dummy_rune", () -> new Item(new Item.Properties().tab(ITEM_GROUP)));
	
	public static final RegistryObject<BlockItem> TOUCHSTONE = ITEMS.register("touchstone", () -> new BlockItem(BlocksRegistry.TOUCHSTONE.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> TOUCHSTONE_BASE= ITEMS.register("touchstone_base", () -> new BlockItem(BlocksRegistry.TOUCHSTONE_BASE.get(), new Item.Properties().tab(ITEM_GROUP)));

	public static final RegistryObject<BlockItem> GRASS = ITEMS.register("usefulgrass", () -> new BlockItem(BlocksRegistry.GRASSUSEFUL.get(), new Item.Properties().tab(ITEM_GROUP)));
	public static final RegistryObject<BlockItem> TALLGRASS = ITEMS.register("usefultallgrass", () -> new BlockItem(BlocksRegistry.TALLGRASSUSEFUL.get(), new Item.Properties().tab(ITEM_GROUP)));

	public static final RegistryObject<Item> GRASS_ITEM = ITEMS.register("grass", () -> new Item(new Item.Properties().tab(ITEM_GROUP)));

	public static final RegistryObject<Item> GRASS_BUNDLE_WEARABLE = ITEMS.register("grass_bundle_wearable", () -> new CustomBundleWearableItem(ArmorMaterialInit.BACKPACK_SIMPLE, new Item.Properties().stacksTo(1).tab(ITEM_GROUP)));
	public static final RegistryObject<Item> GRASS_BUNDLE = ITEMS.register("grass_bundle", () -> new CustomBundleItem(new Item.Properties().stacksTo(1).tab(ITEM_GROUP), 2));

	public static final RegistryObject<BlockItem> COLUMN0 = ITEMS.register("column0", () -> new BlockItem(BlocksRegistry.TOUCHSTONE_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
	public static final RegistryObject<BlockItem> COLUMN1 = ITEMS.register("column1", () -> new BlockItem(BlocksRegistry.TOUCHSTONE_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
	public static final RegistryObject<BlockItem> COLUMN2 = ITEMS.register("column2", () -> new BlockItem(BlocksRegistry.TOUCHSTONE_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));

	public static final RegistryObject<BlockItem> STONECOLUMN0 = ITEMS.register("column/stone_column0", () -> new BlockItem(BlocksRegistry.STONE_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> STONECOLUMN1 = ITEMS.register("column/stone_column1", () -> new BlockItem(BlocksRegistry.STONE_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> STONECOLUMN2 = ITEMS.register("column/stone_column2", () -> new BlockItem(BlocksRegistry.STONE_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> GRANITECOLUMN0 = ITEMS.register("column/granite_column0", () -> new BlockItem(BlocksRegistry.GRANITE_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> GRANITECOLUMN1 = ITEMS.register("column/granite_column1", () -> new BlockItem(BlocksRegistry.GRANITE_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> GRANITECOLUMN2 = ITEMS.register("column/granite_column2", () -> new BlockItem(BlocksRegistry.GRANITE_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> POLISHED_GRANITECOLUMN0 = ITEMS.register("column/polished_granite_column0", () -> new BlockItem(BlocksRegistry.POLISHED_GRANITE_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> POLISHED_GRANITECOLUMN1 = ITEMS.register("column/polished_granite_column1", () -> new BlockItem(BlocksRegistry.POLISHED_GRANITE_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> POLISHED_GRANITECOLUMN2 = ITEMS.register("column/polished_granite_column2", () -> new BlockItem(BlocksRegistry.POLISHED_GRANITE_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> DIORITECOLUMN0 = ITEMS.register("column/diorite_column0", () -> new BlockItem(BlocksRegistry.DIORITE_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> DIORITECOLUMN1 = ITEMS.register("column/diorite_column1", () -> new BlockItem(BlocksRegistry.DIORITE_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> DIORITECOLUMN2 = ITEMS.register("column/diorite_column2", () -> new BlockItem(BlocksRegistry.DIORITE_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> POLISHED_DIORITECOLUMN0 = ITEMS.register("column/polished_diorite_column0", () -> new BlockItem(BlocksRegistry.POLISHED_DIORITE_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> POLISHED_DIORITECOLUMN1 = ITEMS.register("column/polished_diorite_column1", () -> new BlockItem(BlocksRegistry.POLISHED_DIORITE_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> POLISHED_DIORITECOLUMN2 = ITEMS.register("column/polished_diorite_column2", () -> new BlockItem(BlocksRegistry.POLISHED_DIORITE_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> ANDESITECOLUMN0 = ITEMS.register("column/andesite_column0", () -> new BlockItem(BlocksRegistry.ANDESITE_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> ANDESITECOLUMN1 = ITEMS.register("column/andesite_column1", () -> new BlockItem(BlocksRegistry.ANDESITE_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> ANDESITECOLUMN2 = ITEMS.register("column/andesite_column2", () -> new BlockItem(BlocksRegistry.ANDESITE_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> POLISHED_ANDESITECOLUMN0 = ITEMS.register("column/polished_andesite_column0", () -> new BlockItem(BlocksRegistry.POLISHED_ANDESITE_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> POLISHED_ANDESITECOLUMN1 = ITEMS.register("column/polished_andesite_column1", () -> new BlockItem(BlocksRegistry.POLISHED_ANDESITE_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> POLISHED_ANDESITECOLUMN2 = ITEMS.register("column/polished_andesite_column2", () -> new BlockItem(BlocksRegistry.POLISHED_ANDESITE_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> COBBLESTONECOLUMN0 = ITEMS.register("column/cobblestone_column0", () -> new BlockItem(BlocksRegistry.COBBLESTONE_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> COBBLESTONECOLUMN1 = ITEMS.register("column/cobblestone_column1", () -> new BlockItem(BlocksRegistry.COBBLESTONE_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> COBBLESTONECOLUMN2 = ITEMS.register("column/cobblestone_column2", () -> new BlockItem(BlocksRegistry.COBBLESTONE_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
//    public static final RegistryObject<BlockItem> STRIPPED_SPRUCE_LOGCOLUMN0 = ITEMS.register("column/stripped_spruce_log_column0", () -> new BlockItem(BlocksRegistry.STRIPPED_SPRUCE_LOG_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
//    public static final RegistryObject<BlockItem> STRIPPED_SPRUCE_LOGCOLUMN1 = ITEMS.register("column/stripped_spruce_log_column1", () -> new BlockItem(BlocksRegistry.STRIPPED_SPRUCE_LOG_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
//    public static final RegistryObject<BlockItem> STRIPPED_SPRUCE_LOGCOLUMN2 = ITEMS.register("column/stripped_spruce_log_column2", () -> new BlockItem(BlocksRegistry.STRIPPED_SPRUCE_LOG_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
//    public static final RegistryObject<BlockItem> STRIPPED_BIRCH_LOGCOLUMN0 = ITEMS.register("column/stripped_birch_log_column0", () -> new BlockItem(BlocksRegistry.STRIPPED_BIRCH_LOG_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
//    public static final RegistryObject<BlockItem> STRIPPED_BIRCH_LOGCOLUMN1 = ITEMS.register("column/stripped_birch_log_column1", () -> new BlockItem(BlocksRegistry.STRIPPED_BIRCH_LOG_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
//    public static final RegistryObject<BlockItem> STRIPPED_BIRCH_LOGCOLUMN2 = ITEMS.register("column/stripped_birch_log_column2", () -> new BlockItem(BlocksRegistry.STRIPPED_BIRCH_LOG_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
//    public static final RegistryObject<BlockItem> STRIPPED_JUNGLE_LOGCOLUMN0 = ITEMS.register("column/stripped_jungle_log_column0", () -> new BlockItem(BlocksRegistry.STRIPPED_JUNGLE_LOG_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
//    public static final RegistryObject<BlockItem> STRIPPED_JUNGLE_LOGCOLUMN1 = ITEMS.register("column/stripped_jungle_log_column1", () -> new BlockItem(BlocksRegistry.STRIPPED_JUNGLE_LOG_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
//    public static final RegistryObject<BlockItem> STRIPPED_JUNGLE_LOGCOLUMN2 = ITEMS.register("column/stripped_jungle_log_column2", () -> new BlockItem(BlocksRegistry.STRIPPED_JUNGLE_LOG_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
//    public static final RegistryObject<BlockItem> STRIPPED_ACACIA_LOGCOLUMN0 = ITEMS.register("column/stripped_acacia_log_column0", () -> new BlockItem(BlocksRegistry.STRIPPED_ACACIA_LOG_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
//    public static final RegistryObject<BlockItem> STRIPPED_ACACIA_LOGCOLUMN1 = ITEMS.register("column/stripped_acacia_log_column1", () -> new BlockItem(BlocksRegistry.STRIPPED_ACACIA_LOG_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
//    public static final RegistryObject<BlockItem> STRIPPED_ACACIA_LOGCOLUMN2 = ITEMS.register("column/stripped_acacia_log_column2", () -> new BlockItem(BlocksRegistry.STRIPPED_ACACIA_LOG_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
//    public static final RegistryObject<BlockItem> STRIPPED_DARK_OAK_LOGCOLUMN0 = ITEMS.register("column/stripped_dark_oak_log_column0", () -> new BlockItem(BlocksRegistry.STRIPPED_DARK_OAK_LOG_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
//    public static final RegistryObject<BlockItem> STRIPPED_DARK_OAK_LOGCOLUMN1 = ITEMS.register("column/stripped_dark_oak_log_column1", () -> new BlockItem(BlocksRegistry.STRIPPED_DARK_OAK_LOG_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
//    public static final RegistryObject<BlockItem> STRIPPED_DARK_OAK_LOGCOLUMN2 = ITEMS.register("column/stripped_dark_oak_log_column2", () -> new BlockItem(BlocksRegistry.STRIPPED_DARK_OAK_LOG_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
//    public static final RegistryObject<BlockItem> STRIPPED_OAK_LOGCOLUMN0 = ITEMS.register("column/stripped_oak_log_column0", () -> new BlockItem(BlocksRegistry.STRIPPED_OAK_LOG_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
//    public static final RegistryObject<BlockItem> STRIPPED_OAK_LOGCOLUMN1 = ITEMS.register("column/stripped_oak_log_column1", () -> new BlockItem(BlocksRegistry.STRIPPED_OAK_LOG_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
//    public static final RegistryObject<BlockItem> STRIPPED_OAK_LOGCOLUMN2 = ITEMS.register("column/stripped_oak_log_column2", () -> new BlockItem(BlocksRegistry.STRIPPED_OAK_LOG_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> LAPIS_BLOCKCOLUMN0 = ITEMS.register("column/lapis_block_column0", () -> new BlockItem(BlocksRegistry.LAPIS_BLOCK_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> LAPIS_BLOCKCOLUMN1 = ITEMS.register("column/lapis_block_column1", () -> new BlockItem(BlocksRegistry.LAPIS_BLOCK_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> LAPIS_BLOCKCOLUMN2 = ITEMS.register("column/lapis_block_column2", () -> new BlockItem(BlocksRegistry.LAPIS_BLOCK_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> GOLD_BLOCKCOLUMN0 = ITEMS.register("column/gold_block_column0", () -> new BlockItem(BlocksRegistry.GOLD_BLOCK_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> GOLD_BLOCKCOLUMN1 = ITEMS.register("column/gold_block_column1", () -> new BlockItem(BlocksRegistry.GOLD_BLOCK_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> GOLD_BLOCKCOLUMN2 = ITEMS.register("column/gold_block_column2", () -> new BlockItem(BlocksRegistry.GOLD_BLOCK_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> IRON_BLOCKCOLUMN0 = ITEMS.register("column/iron_block_column0", () -> new BlockItem(BlocksRegistry.IRON_BLOCK_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> IRON_BLOCKCOLUMN1 = ITEMS.register("column/iron_block_column1", () -> new BlockItem(BlocksRegistry.IRON_BLOCK_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> IRON_BLOCKCOLUMN2 = ITEMS.register("column/iron_block_column2", () -> new BlockItem(BlocksRegistry.IRON_BLOCK_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> DIAMOND_BLOCKCOLUMN0 = ITEMS.register("column/diamond_block_column0", () -> new BlockItem(BlocksRegistry.DIAMOND_BLOCK_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> DIAMOND_BLOCKCOLUMN1 = ITEMS.register("column/diamond_block_column1", () -> new BlockItem(BlocksRegistry.DIAMOND_BLOCK_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> DIAMOND_BLOCKCOLUMN2 = ITEMS.register("column/diamond_block_column2", () -> new BlockItem(BlocksRegistry.DIAMOND_BLOCK_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> NETHERITE_BLOCKCOLUMN0 = ITEMS.register("column/netherite_block_column0", () -> new BlockItem(BlocksRegistry.NETHERITE_BLOCK_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> NETHERITE_BLOCKCOLUMN1 = ITEMS.register("column/netherite_block_column1", () -> new BlockItem(BlocksRegistry.NETHERITE_BLOCK_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> NETHERITE_BLOCKCOLUMN2 = ITEMS.register("column/netherite_block_column2", () -> new BlockItem(BlocksRegistry.NETHERITE_BLOCK_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> SANDSTONECOLUMN0 = ITEMS.register("column/sandstone_column0", () -> new BlockItem(BlocksRegistry.SANDSTONE_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> SANDSTONECOLUMN1 = ITEMS.register("column/sandstone_column1", () -> new BlockItem(BlocksRegistry.SANDSTONE_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> SANDSTONECOLUMN2 = ITEMS.register("column/sandstone_column2", () -> new BlockItem(BlocksRegistry.SANDSTONE_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CHISELED_SANDSTONECOLUMN0 = ITEMS.register("column/chiseled_sandstone_column0", () -> new BlockItem(BlocksRegistry.CHISELED_SANDSTONE_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CHISELED_SANDSTONECOLUMN1 = ITEMS.register("column/chiseled_sandstone_column1", () -> new BlockItem(BlocksRegistry.CHISELED_SANDSTONE_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CHISELED_SANDSTONECOLUMN2 = ITEMS.register("column/chiseled_sandstone_column2", () -> new BlockItem(BlocksRegistry.CHISELED_SANDSTONE_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CUT_SANDSTONECOLUMN0 = ITEMS.register("column/cut_sandstone_column0", () -> new BlockItem(BlocksRegistry.CUT_SANDSTONE_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CUT_SANDSTONECOLUMN1 = ITEMS.register("column/cut_sandstone_column1", () -> new BlockItem(BlocksRegistry.CUT_SANDSTONE_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CUT_SANDSTONECOLUMN2 = ITEMS.register("column/cut_sandstone_column2", () -> new BlockItem(BlocksRegistry.CUT_SANDSTONE_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> SMOOTH_SANDSTONECOLUMN0 = ITEMS.register("column/smooth_sandstone_column0", () -> new BlockItem(BlocksRegistry.SMOOTH_SANDSTONE_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> SMOOTH_SANDSTONECOLUMN1 = ITEMS.register("column/smooth_sandstone_column1", () -> new BlockItem(BlocksRegistry.SMOOTH_SANDSTONE_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> SMOOTH_SANDSTONECOLUMN2 = ITEMS.register("column/smooth_sandstone_column2", () -> new BlockItem(BlocksRegistry.SMOOTH_SANDSTONE_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> BRICKSCOLUMN0 = ITEMS.register("column/bricks_column0", () -> new BlockItem(BlocksRegistry.BRICKS_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> BRICKSCOLUMN1 = ITEMS.register("column/bricks_column1", () -> new BlockItem(BlocksRegistry.BRICKS_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> BRICKSCOLUMN2 = ITEMS.register("column/bricks_column2", () -> new BlockItem(BlocksRegistry.BRICKS_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> MOSSY_COBBLESTONECOLUMN0 = ITEMS.register("column/mossy_cobblestone_column0", () -> new BlockItem(BlocksRegistry.MOSSY_COBBLESTONE_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> MOSSY_COBBLESTONECOLUMN1 = ITEMS.register("column/mossy_cobblestone_column1", () -> new BlockItem(BlocksRegistry.MOSSY_COBBLESTONE_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> MOSSY_COBBLESTONECOLUMN2 = ITEMS.register("column/mossy_cobblestone_column2", () -> new BlockItem(BlocksRegistry.MOSSY_COBBLESTONE_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> OBSIDIANCOLUMN0 = ITEMS.register("column/obsidian_column0", () -> new BlockItem(BlocksRegistry.OBSIDIAN_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> OBSIDIANCOLUMN1 = ITEMS.register("column/obsidian_column1", () -> new BlockItem(BlocksRegistry.OBSIDIAN_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> OBSIDIANCOLUMN2 = ITEMS.register("column/obsidian_column2", () -> new BlockItem(BlocksRegistry.OBSIDIAN_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> BASALTCOLUMN0 = ITEMS.register("column/basalt_column0", () -> new BlockItem(BlocksRegistry.BASALT_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> BASALTCOLUMN1 = ITEMS.register("column/basalt_column1", () -> new BlockItem(BlocksRegistry.BASALT_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> BASALTCOLUMN2 = ITEMS.register("column/basalt_column2", () -> new BlockItem(BlocksRegistry.BASALT_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> POLISHED_BASALTCOLUMN0 = ITEMS.register("column/polished_basalt_column0", () -> new BlockItem(BlocksRegistry.POLISHED_BASALT_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> POLISHED_BASALTCOLUMN1 = ITEMS.register("column/polished_basalt_column1", () -> new BlockItem(BlocksRegistry.POLISHED_BASALT_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> POLISHED_BASALTCOLUMN2 = ITEMS.register("column/polished_basalt_column2", () -> new BlockItem(BlocksRegistry.POLISHED_BASALT_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> STONE_BRICKSCOLUMN0 = ITEMS.register("column/stone_bricks_column0", () -> new BlockItem(BlocksRegistry.STONE_BRICKS_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> STONE_BRICKSCOLUMN1 = ITEMS.register("column/stone_bricks_column1", () -> new BlockItem(BlocksRegistry.STONE_BRICKS_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> STONE_BRICKSCOLUMN2 = ITEMS.register("column/stone_bricks_column2", () -> new BlockItem(BlocksRegistry.STONE_BRICKS_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> MOSSY_STONE_BRICKSCOLUMN0 = ITEMS.register("column/mossy_stone_bricks_column0", () -> new BlockItem(BlocksRegistry.MOSSY_STONE_BRICKS_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> MOSSY_STONE_BRICKSCOLUMN1 = ITEMS.register("column/mossy_stone_bricks_column1", () -> new BlockItem(BlocksRegistry.MOSSY_STONE_BRICKS_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> MOSSY_STONE_BRICKSCOLUMN2 = ITEMS.register("column/mossy_stone_bricks_column2", () -> new BlockItem(BlocksRegistry.MOSSY_STONE_BRICKS_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CRACKED_STONE_BRICKSCOLUMN0 = ITEMS.register("column/cracked_stone_bricks_column0", () -> new BlockItem(BlocksRegistry.CRACKED_STONE_BRICKS_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CRACKED_STONE_BRICKSCOLUMN1 = ITEMS.register("column/cracked_stone_bricks_column1", () -> new BlockItem(BlocksRegistry.CRACKED_STONE_BRICKS_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CRACKED_STONE_BRICKSCOLUMN2 = ITEMS.register("column/cracked_stone_bricks_column2", () -> new BlockItem(BlocksRegistry.CRACKED_STONE_BRICKS_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CHISELED_STONE_BRICKSCOLUMN0 = ITEMS.register("column/chiseled_stone_bricks_column0", () -> new BlockItem(BlocksRegistry.CHISELED_STONE_BRICKS_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CHISELED_STONE_BRICKSCOLUMN1 = ITEMS.register("column/chiseled_stone_bricks_column1", () -> new BlockItem(BlocksRegistry.CHISELED_STONE_BRICKS_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CHISELED_STONE_BRICKSCOLUMN2 = ITEMS.register("column/chiseled_stone_bricks_column2", () -> new BlockItem(BlocksRegistry.CHISELED_STONE_BRICKS_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> NETHER_BRICKSCOLUMN0 = ITEMS.register("column/nether_bricks_column0", () -> new BlockItem(BlocksRegistry.NETHER_BRICKS_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> NETHER_BRICKSCOLUMN1 = ITEMS.register("column/nether_bricks_column1", () -> new BlockItem(BlocksRegistry.NETHER_BRICKS_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> NETHER_BRICKSCOLUMN2 = ITEMS.register("column/nether_bricks_column2", () -> new BlockItem(BlocksRegistry.NETHER_BRICKS_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> EMERALD_BLOCKCOLUMN0 = ITEMS.register("column/emerald_block_column0", () -> new BlockItem(BlocksRegistry.EMERALD_BLOCK_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> EMERALD_BLOCKCOLUMN1 = ITEMS.register("column/emerald_block_column1", () -> new BlockItem(BlocksRegistry.EMERALD_BLOCK_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> EMERALD_BLOCKCOLUMN2 = ITEMS.register("column/emerald_block_column2", () -> new BlockItem(BlocksRegistry.EMERALD_BLOCK_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> QUARTZ_BLOCKCOLUMN0 = ITEMS.register("column/quartz_block_column0", () -> new BlockItem(BlocksRegistry.QUARTZ_BLOCK_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> QUARTZ_BLOCKCOLUMN1 = ITEMS.register("column/quartz_block_column1", () -> new BlockItem(BlocksRegistry.QUARTZ_BLOCK_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> QUARTZ_BLOCKCOLUMN2 = ITEMS.register("column/quartz_block_column2", () -> new BlockItem(BlocksRegistry.QUARTZ_BLOCK_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> QUARTZ_PILLARCOLUMN0 = ITEMS.register("column/quartz_pillar_column0", () -> new BlockItem(BlocksRegistry.QUARTZ_PILLAR_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> QUARTZ_PILLARCOLUMN1 = ITEMS.register("column/quartz_pillar_column1", () -> new BlockItem(BlocksRegistry.QUARTZ_PILLAR_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> QUARTZ_PILLARCOLUMN2 = ITEMS.register("column/quartz_pillar_column2", () -> new BlockItem(BlocksRegistry.QUARTZ_PILLAR_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> SMOOTH_QUARTZ_BLOCKCOLUMN0 = ITEMS.register("column/smooth_quartz_block_column0", () -> new BlockItem(BlocksRegistry.SMOOTH_QUARTZ_BLOCK_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> SMOOTH_QUARTZ_BLOCKCOLUMN1 = ITEMS.register("column/smooth_quartz_block_column1", () -> new BlockItem(BlocksRegistry.SMOOTH_QUARTZ_BLOCK_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> SMOOTH_QUARTZ_BLOCKCOLUMN2 = ITEMS.register("column/smooth_quartz_block_column2", () -> new BlockItem(BlocksRegistry.SMOOTH_QUARTZ_BLOCK_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CHISELED_QUARTZ_BLOCKCOLUMN0 = ITEMS.register("column/chiseled_quartz_block_column0", () -> new BlockItem(BlocksRegistry.CHISELED_QUARTZ_BLOCK_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CHISELED_QUARTZ_BLOCKCOLUMN1 = ITEMS.register("column/chiseled_quartz_block_column1", () -> new BlockItem(BlocksRegistry.CHISELED_QUARTZ_BLOCK_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CHISELED_QUARTZ_BLOCKCOLUMN2 = ITEMS.register("column/chiseled_quartz_block_column2", () -> new BlockItem(BlocksRegistry.CHISELED_QUARTZ_BLOCK_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> PRISMARINECOLUMN0 = ITEMS.register("column/prismarine_column0", () -> new BlockItem(BlocksRegistry.PRISMARINE_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> PRISMARINECOLUMN1 = ITEMS.register("column/prismarine_column1", () -> new BlockItem(BlocksRegistry.PRISMARINE_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> PRISMARINECOLUMN2 = ITEMS.register("column/prismarine_column2", () -> new BlockItem(BlocksRegistry.PRISMARINE_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> PRISMARINE_BRICKSCOLUMN0 = ITEMS.register("column/prismarine_bricks_column0", () -> new BlockItem(BlocksRegistry.PRISMARINE_BRICKS_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> PRISMARINE_BRICKSCOLUMN1 = ITEMS.register("column/prismarine_bricks_column1", () -> new BlockItem(BlocksRegistry.PRISMARINE_BRICKS_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> PRISMARINE_BRICKSCOLUMN2 = ITEMS.register("column/prismarine_bricks_column2", () -> new BlockItem(BlocksRegistry.PRISMARINE_BRICKS_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> DARK_PRISMARINECOLUMN0 = ITEMS.register("column/dark_prismarine_column0", () -> new BlockItem(BlocksRegistry.DARK_PRISMARINE_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> DARK_PRISMARINECOLUMN1 = ITEMS.register("column/dark_prismarine_column1", () -> new BlockItem(BlocksRegistry.DARK_PRISMARINE_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> DARK_PRISMARINECOLUMN2 = ITEMS.register("column/dark_prismarine_column2", () -> new BlockItem(BlocksRegistry.DARK_PRISMARINE_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> COAL_BLOCKCOLUMN0 = ITEMS.register("column/coal_block_column0", () -> new BlockItem(BlocksRegistry.COAL_BLOCK_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> COAL_BLOCKCOLUMN1 = ITEMS.register("column/coal_block_column1", () -> new BlockItem(BlocksRegistry.COAL_BLOCK_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> COAL_BLOCKCOLUMN2 = ITEMS.register("column/coal_block_column2", () -> new BlockItem(BlocksRegistry.COAL_BLOCK_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CHISELED_RED_SANDSTONECOLUMN0 = ITEMS.register("column/chiseled_red_sandstone_column0", () -> new BlockItem(BlocksRegistry.CHISELED_RED_SANDSTONE_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CHISELED_RED_SANDSTONECOLUMN1 = ITEMS.register("column/chiseled_red_sandstone_column1", () -> new BlockItem(BlocksRegistry.CHISELED_RED_SANDSTONE_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CHISELED_RED_SANDSTONECOLUMN2 = ITEMS.register("column/chiseled_red_sandstone_column2", () -> new BlockItem(BlocksRegistry.CHISELED_RED_SANDSTONE_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> RED_SANDSTONECOLUMN0 = ITEMS.register("column/red_sandstone_column0", () -> new BlockItem(BlocksRegistry.RED_SANDSTONE_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> RED_SANDSTONECOLUMN1 = ITEMS.register("column/red_sandstone_column1", () -> new BlockItem(BlocksRegistry.RED_SANDSTONE_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> RED_SANDSTONECOLUMN2 = ITEMS.register("column/red_sandstone_column2", () -> new BlockItem(BlocksRegistry.RED_SANDSTONE_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CUT_RED_SANDSTONECOLUMN0 = ITEMS.register("column/cut_red_sandstone_column0", () -> new BlockItem(BlocksRegistry.CUT_RED_SANDSTONE_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CUT_RED_SANDSTONECOLUMN1 = ITEMS.register("column/cut_red_sandstone_column1", () -> new BlockItem(BlocksRegistry.CUT_RED_SANDSTONE_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CUT_RED_SANDSTONECOLUMN2 = ITEMS.register("column/cut_red_sandstone_column2", () -> new BlockItem(BlocksRegistry.CUT_RED_SANDSTONE_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> SMOOTH_RED_SANDSTONECOLUMN0 = ITEMS.register("column/smooth_red_sandstone_column0", () -> new BlockItem(BlocksRegistry.SMOOTH_RED_SANDSTONE_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> SMOOTH_RED_SANDSTONECOLUMN1 = ITEMS.register("column/smooth_red_sandstone_column1", () -> new BlockItem(BlocksRegistry.SMOOTH_RED_SANDSTONE_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> SMOOTH_RED_SANDSTONECOLUMN2 = ITEMS.register("column/smooth_red_sandstone_column2", () -> new BlockItem(BlocksRegistry.SMOOTH_RED_SANDSTONE_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> END_STONE_BRICKSCOLUMN0 = ITEMS.register("column/end_stone_bricks_column0", () -> new BlockItem(BlocksRegistry.END_STONE_BRICKS_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> END_STONE_BRICKSCOLUMN1 = ITEMS.register("column/end_stone_bricks_column1", () -> new BlockItem(BlocksRegistry.END_STONE_BRICKS_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> END_STONE_BRICKSCOLUMN2 = ITEMS.register("column/end_stone_bricks_column2", () -> new BlockItem(BlocksRegistry.END_STONE_BRICKS_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> RED_NETHER_BRICKSCOLUMN0 = ITEMS.register("column/red_nether_bricks_column0", () -> new BlockItem(BlocksRegistry.RED_NETHER_BRICKS_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> RED_NETHER_BRICKSCOLUMN1 = ITEMS.register("column/red_nether_bricks_column1", () -> new BlockItem(BlocksRegistry.RED_NETHER_BRICKS_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> RED_NETHER_BRICKSCOLUMN2 = ITEMS.register("column/red_nether_bricks_column2", () -> new BlockItem(BlocksRegistry.RED_NETHER_BRICKS_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> STRIPPED_CRIMSON_STEMCOLUMN0 = ITEMS.register("column/stripped_crimson_stem_column0", () -> new BlockItem(BlocksRegistry.STRIPPED_CRIMSON_STEM_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> STRIPPED_CRIMSON_STEMCOLUMN1 = ITEMS.register("column/stripped_crimson_stem_column1", () -> new BlockItem(BlocksRegistry.STRIPPED_CRIMSON_STEM_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> STRIPPED_CRIMSON_STEMCOLUMN2 = ITEMS.register("column/stripped_crimson_stem_column2", () -> new BlockItem(BlocksRegistry.STRIPPED_CRIMSON_STEM_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> STRIPPED_WARPED_STEMCOLUMN0 = ITEMS.register("column/stripped_warped_stem_column0", () -> new BlockItem(BlocksRegistry.STRIPPED_WARPED_STEM_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> STRIPPED_WARPED_STEMCOLUMN1 = ITEMS.register("column/stripped_warped_stem_column1", () -> new BlockItem(BlocksRegistry.STRIPPED_WARPED_STEM_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> STRIPPED_WARPED_STEMCOLUMN2 = ITEMS.register("column/stripped_warped_stem_column2", () -> new BlockItem(BlocksRegistry.STRIPPED_WARPED_STEM_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> ANCIENT_DEBRISCOLUMN0 = ITEMS.register("column/ancient_debris_column0", () -> new BlockItem(BlocksRegistry.ANCIENT_DEBRIS_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> ANCIENT_DEBRISCOLUMN1 = ITEMS.register("column/ancient_debris_column1", () -> new BlockItem(BlocksRegistry.ANCIENT_DEBRIS_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> ANCIENT_DEBRISCOLUMN2 = ITEMS.register("column/ancient_debris_column2", () -> new BlockItem(BlocksRegistry.ANCIENT_DEBRIS_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CRYING_OBSIDIANCOLUMN0 = ITEMS.register("column/crying_obsidian_column0", () -> new BlockItem(BlocksRegistry.CRYING_OBSIDIAN_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CRYING_OBSIDIANCOLUMN1 = ITEMS.register("column/crying_obsidian_column1", () -> new BlockItem(BlocksRegistry.CRYING_OBSIDIAN_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CRYING_OBSIDIANCOLUMN2 = ITEMS.register("column/crying_obsidian_column2", () -> new BlockItem(BlocksRegistry.CRYING_OBSIDIAN_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CHISELED_POLISHED_BLACKSTONECOLUMN0 = ITEMS.register("column/chiseled_polished_blackstone_column0", () -> new BlockItem(BlocksRegistry.CHISELED_POLISHED_BLACKSTONE_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CHISELED_POLISHED_BLACKSTONECOLUMN1 = ITEMS.register("column/chiseled_polished_blackstone_column1", () -> new BlockItem(BlocksRegistry.CHISELED_POLISHED_BLACKSTONE_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CHISELED_POLISHED_BLACKSTONECOLUMN2 = ITEMS.register("column/chiseled_polished_blackstone_column2", () -> new BlockItem(BlocksRegistry.CHISELED_POLISHED_BLACKSTONE_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> POLISHED_BLACKSTONECOLUMN0 = ITEMS.register("column/polished_blackstone_column0", () -> new BlockItem(BlocksRegistry.POLISHED_BLACKSTONE_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> POLISHED_BLACKSTONECOLUMN1 = ITEMS.register("column/polished_blackstone_column1", () -> new BlockItem(BlocksRegistry.POLISHED_BLACKSTONE_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> POLISHED_BLACKSTONECOLUMN2 = ITEMS.register("column/polished_blackstone_column2", () -> new BlockItem(BlocksRegistry.POLISHED_BLACKSTONE_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CRACKED_POLISHED_BLACKSTONE_BRICKSCOLUMN0 = ITEMS.register("column/cracked_polished_blackstone_bricks_column0", () -> new BlockItem(BlocksRegistry.CRACKED_POLISHED_BLACKSTONE_BRICKS_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CRACKED_POLISHED_BLACKSTONE_BRICKSCOLUMN1 = ITEMS.register("column/cracked_polished_blackstone_bricks_column1", () -> new BlockItem(BlocksRegistry.CRACKED_POLISHED_BLACKSTONE_BRICKS_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CRACKED_POLISHED_BLACKSTONE_BRICKSCOLUMN2 = ITEMS.register("column/cracked_polished_blackstone_bricks_column2", () -> new BlockItem(BlocksRegistry.CRACKED_POLISHED_BLACKSTONE_BRICKS_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> POLISHED_BLACKSTONE_BRICKSCOLUMN0 = ITEMS.register("column/polished_blackstone_bricks_column0", () -> new BlockItem(BlocksRegistry.POLISHED_BLACKSTONE_BRICKS_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> POLISHED_BLACKSTONE_BRICKSCOLUMN1 = ITEMS.register("column/polished_blackstone_bricks_column1", () -> new BlockItem(BlocksRegistry.POLISHED_BLACKSTONE_BRICKS_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> POLISHED_BLACKSTONE_BRICKSCOLUMN2 = ITEMS.register("column/polished_blackstone_bricks_column2", () -> new BlockItem(BlocksRegistry.POLISHED_BLACKSTONE_BRICKS_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> QUARTZ_BRICKSCOLUMN0 = ITEMS.register("column/quartz_bricks_column0", () -> new BlockItem(BlocksRegistry.QUARTZ_BRICKS_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> QUARTZ_BRICKSCOLUMN1 = ITEMS.register("column/quartz_bricks_column1", () -> new BlockItem(BlocksRegistry.QUARTZ_BRICKS_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> QUARTZ_BRICKSCOLUMN2 = ITEMS.register("column/quartz_bricks_column2", () -> new BlockItem(BlocksRegistry.QUARTZ_BRICKS_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CHISELED_NETHER_BRICKSCOLUMN0 = ITEMS.register("column/chiseled_nether_bricks_column0", () -> new BlockItem(BlocksRegistry.CHISELED_NETHER_BRICKS_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CHISELED_NETHER_BRICKSCOLUMN1 = ITEMS.register("column/chiseled_nether_bricks_column1", () -> new BlockItem(BlocksRegistry.CHISELED_NETHER_BRICKS_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CHISELED_NETHER_BRICKSCOLUMN2 = ITEMS.register("column/chiseled_nether_bricks_column2", () -> new BlockItem(BlocksRegistry.CHISELED_NETHER_BRICKS_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CRACKED_NETHER_BRICKSCOLUMN0 = ITEMS.register("column/cracked_nether_bricks_column0", () -> new BlockItem(BlocksRegistry.CRACKED_NETHER_BRICKS_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CRACKED_NETHER_BRICKSCOLUMN1 = ITEMS.register("column/cracked_nether_bricks_column1", () -> new BlockItem(BlocksRegistry.CRACKED_NETHER_BRICKS_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CRACKED_NETHER_BRICKSCOLUMN2 = ITEMS.register("column/cracked_nether_bricks_column2", () -> new BlockItem(BlocksRegistry.CRACKED_NETHER_BRICKS_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> OXIDIZED_COPPERCOLUMN0 = ITEMS.register("column/oxidized_copper_column0", () -> new BlockItem(BlocksRegistry.OXIDIZED_COPPER_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> OXIDIZED_COPPERCOLUMN1 = ITEMS.register("column/oxidized_copper_column1", () -> new BlockItem(BlocksRegistry.OXIDIZED_COPPER_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> OXIDIZED_COPPERCOLUMN2 = ITEMS.register("column/oxidized_copper_column2", () -> new BlockItem(BlocksRegistry.OXIDIZED_COPPER_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> WEATHERED_COPPERCOLUMN0 = ITEMS.register("column/weathered_copper_column0", () -> new BlockItem(BlocksRegistry.WEATHERED_COPPER_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> WEATHERED_COPPERCOLUMN1 = ITEMS.register("column/weathered_copper_column1", () -> new BlockItem(BlocksRegistry.WEATHERED_COPPER_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> WEATHERED_COPPERCOLUMN2 = ITEMS.register("column/weathered_copper_column2", () -> new BlockItem(BlocksRegistry.WEATHERED_COPPER_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> EXPOSED_COPPERCOLUMN0 = ITEMS.register("column/exposed_copper_column0", () -> new BlockItem(BlocksRegistry.EXPOSED_COPPER_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> EXPOSED_COPPERCOLUMN1 = ITEMS.register("column/exposed_copper_column1", () -> new BlockItem(BlocksRegistry.EXPOSED_COPPER_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> EXPOSED_COPPERCOLUMN2 = ITEMS.register("column/exposed_copper_column2", () -> new BlockItem(BlocksRegistry.EXPOSED_COPPER_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> COPPER_BLOCKCOLUMN0 = ITEMS.register("column/copper_block_column0", () -> new BlockItem(BlocksRegistry.COPPER_BLOCK_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> COPPER_BLOCKCOLUMN1 = ITEMS.register("column/copper_block_column1", () -> new BlockItem(BlocksRegistry.COPPER_BLOCK_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> COPPER_BLOCKCOLUMN2 = ITEMS.register("column/copper_block_column2", () -> new BlockItem(BlocksRegistry.COPPER_BLOCK_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> OXIDIZED_CUT_COPPERCOLUMN0 = ITEMS.register("column/oxidized_cut_copper_column0", () -> new BlockItem(BlocksRegistry.OXIDIZED_CUT_COPPER_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> OXIDIZED_CUT_COPPERCOLUMN1 = ITEMS.register("column/oxidized_cut_copper_column1", () -> new BlockItem(BlocksRegistry.OXIDIZED_CUT_COPPER_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> OXIDIZED_CUT_COPPERCOLUMN2 = ITEMS.register("column/oxidized_cut_copper_column2", () -> new BlockItem(BlocksRegistry.OXIDIZED_CUT_COPPER_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> WEATHERED_CUT_COPPERCOLUMN0 = ITEMS.register("column/weathered_cut_copper_column0", () -> new BlockItem(BlocksRegistry.WEATHERED_CUT_COPPER_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> WEATHERED_CUT_COPPERCOLUMN1 = ITEMS.register("column/weathered_cut_copper_column1", () -> new BlockItem(BlocksRegistry.WEATHERED_CUT_COPPER_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> WEATHERED_CUT_COPPERCOLUMN2 = ITEMS.register("column/weathered_cut_copper_column2", () -> new BlockItem(BlocksRegistry.WEATHERED_CUT_COPPER_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> EXPOSED_CUT_COPPERCOLUMN0 = ITEMS.register("column/exposed_cut_copper_column0", () -> new BlockItem(BlocksRegistry.EXPOSED_CUT_COPPER_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> EXPOSED_CUT_COPPERCOLUMN1 = ITEMS.register("column/exposed_cut_copper_column1", () -> new BlockItem(BlocksRegistry.EXPOSED_CUT_COPPER_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> EXPOSED_CUT_COPPERCOLUMN2 = ITEMS.register("column/exposed_cut_copper_column2", () -> new BlockItem(BlocksRegistry.EXPOSED_CUT_COPPER_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CUT_COPPERCOLUMN0 = ITEMS.register("column/cut_copper_column0", () -> new BlockItem(BlocksRegistry.CUT_COPPER_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CUT_COPPERCOLUMN1 = ITEMS.register("column/cut_copper_column1", () -> new BlockItem(BlocksRegistry.CUT_COPPER_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> CUT_COPPERCOLUMN2 = ITEMS.register("column/cut_copper_column2", () -> new BlockItem(BlocksRegistry.CUT_COPPER_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> WAXED_COPPER_BLOCKCOLUMN0 = ITEMS.register("column/waxed_copper_block_column0", () -> new BlockItem(BlocksRegistry.WAXED_COPPER_BLOCK_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> WAXED_COPPER_BLOCKCOLUMN1 = ITEMS.register("column/waxed_copper_block_column1", () -> new BlockItem(BlocksRegistry.WAXED_COPPER_BLOCK_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> WAXED_COPPER_BLOCKCOLUMN2 = ITEMS.register("column/waxed_copper_block_column2", () -> new BlockItem(BlocksRegistry.WAXED_COPPER_BLOCK_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> WAXED_WEATHERED_COPPERCOLUMN0 = ITEMS.register("column/waxed_weathered_copper_column0", () -> new BlockItem(BlocksRegistry.WAXED_WEATHERED_COPPER_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> WAXED_WEATHERED_COPPERCOLUMN1 = ITEMS.register("column/waxed_weathered_copper_column1", () -> new BlockItem(BlocksRegistry.WAXED_WEATHERED_COPPER_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> WAXED_WEATHERED_COPPERCOLUMN2 = ITEMS.register("column/waxed_weathered_copper_column2", () -> new BlockItem(BlocksRegistry.WAXED_WEATHERED_COPPER_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> WAXED_EXPOSED_COPPERCOLUMN0 = ITEMS.register("column/waxed_exposed_copper_column0", () -> new BlockItem(BlocksRegistry.WAXED_EXPOSED_COPPER_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> WAXED_EXPOSED_COPPERCOLUMN1 = ITEMS.register("column/waxed_exposed_copper_column1", () -> new BlockItem(BlocksRegistry.WAXED_EXPOSED_COPPER_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> WAXED_EXPOSED_COPPERCOLUMN2 = ITEMS.register("column/waxed_exposed_copper_column2", () -> new BlockItem(BlocksRegistry.WAXED_EXPOSED_COPPER_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> WAXED_OXIDIZED_COPPERCOLUMN0 = ITEMS.register("column/waxed_oxidized_copper_column0", () -> new BlockItem(BlocksRegistry.WAXED_OXIDIZED_COPPER_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> WAXED_OXIDIZED_COPPERCOLUMN1 = ITEMS.register("column/waxed_oxidized_copper_column1", () -> new BlockItem(BlocksRegistry.WAXED_OXIDIZED_COPPER_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> WAXED_OXIDIZED_COPPERCOLUMN2 = ITEMS.register("column/waxed_oxidized_copper_column2", () -> new BlockItem(BlocksRegistry.WAXED_OXIDIZED_COPPER_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> WAXED_OXIDIZED_CUT_COPPERCOLUMN0 = ITEMS.register("column/waxed_oxidized_cut_copper_column0", () -> new BlockItem(BlocksRegistry.WAXED_OXIDIZED_CUT_COPPER_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> WAXED_OXIDIZED_CUT_COPPERCOLUMN1 = ITEMS.register("column/waxed_oxidized_cut_copper_column1", () -> new BlockItem(BlocksRegistry.WAXED_OXIDIZED_CUT_COPPER_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> WAXED_OXIDIZED_CUT_COPPERCOLUMN2 = ITEMS.register("column/waxed_oxidized_cut_copper_column2", () -> new BlockItem(BlocksRegistry.WAXED_OXIDIZED_CUT_COPPER_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> WAXED_WEATHERED_CUT_COPPERCOLUMN0 = ITEMS.register("column/waxed_weathered_cut_copper_column0", () -> new BlockItem(BlocksRegistry.WAXED_WEATHERED_CUT_COPPER_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> WAXED_WEATHERED_CUT_COPPERCOLUMN1 = ITEMS.register("column/waxed_weathered_cut_copper_column1", () -> new BlockItem(BlocksRegistry.WAXED_WEATHERED_CUT_COPPER_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> WAXED_WEATHERED_CUT_COPPERCOLUMN2 = ITEMS.register("column/waxed_weathered_cut_copper_column2", () -> new BlockItem(BlocksRegistry.WAXED_WEATHERED_CUT_COPPER_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> WAXED_EXPOSED_CUT_COPPERCOLUMN0 = ITEMS.register("column/waxed_exposed_cut_copper_column0", () -> new BlockItem(BlocksRegistry.WAXED_EXPOSED_CUT_COPPER_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> WAXED_EXPOSED_CUT_COPPERCOLUMN1 = ITEMS.register("column/waxed_exposed_cut_copper_column1", () -> new BlockItem(BlocksRegistry.WAXED_EXPOSED_CUT_COPPER_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> WAXED_EXPOSED_CUT_COPPERCOLUMN2 = ITEMS.register("column/waxed_exposed_cut_copper_column2", () -> new BlockItem(BlocksRegistry.WAXED_EXPOSED_CUT_COPPER_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> WAXED_CUT_COPPERCOLUMN0 = ITEMS.register("column/waxed_cut_copper_column0", () -> new BlockItem(BlocksRegistry.WAXED_CUT_COPPER_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> WAXED_CUT_COPPERCOLUMN1 = ITEMS.register("column/waxed_cut_copper_column1", () -> new BlockItem(BlocksRegistry.WAXED_CUT_COPPER_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> WAXED_CUT_COPPERCOLUMN2 = ITEMS.register("column/waxed_cut_copper_column2", () -> new BlockItem(BlocksRegistry.WAXED_CUT_COPPER_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> SMOOTH_BASALTCOLUMN0 = ITEMS.register("column/smooth_basalt_column0", () -> new BlockItem(BlocksRegistry.SMOOTH_BASALT_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> SMOOTH_BASALTCOLUMN1 = ITEMS.register("column/smooth_basalt_column1", () -> new BlockItem(BlocksRegistry.SMOOTH_BASALT_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> SMOOTH_BASALTCOLUMN2 = ITEMS.register("column/smooth_basalt_column2", () -> new BlockItem(BlocksRegistry.SMOOTH_BASALT_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> PURPUR_BLOCKCOLUMN0 = ITEMS.register("column/purpur_block_column0", () -> new BlockItem(BlocksRegistry.PURPUR_BLOCK_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> PURPUR_BLOCKCOLUMN1 = ITEMS.register("column/purpur_block_column1", () -> new BlockItem(BlocksRegistry.PURPUR_BLOCK_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> PURPUR_BLOCKCOLUMN2 = ITEMS.register("column/purpur_block_column2", () -> new BlockItem(BlocksRegistry.PURPUR_BLOCK_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> PURPUR_PILLARCOLUMN0 = ITEMS.register("column/purpur_pillar_column0", () -> new BlockItem(BlocksRegistry.PURPUR_PILLAR_COLUMN0.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> PURPUR_PILLARCOLUMN1 = ITEMS.register("column/purpur_pillar_column1", () -> new BlockItem(BlocksRegistry.PURPUR_PILLAR_COLUMN1.get(), new Item.Properties().tab(ITEM_GROUP)));
    public static final RegistryObject<BlockItem> PURPUR_PILLARCOLUMN2 = ITEMS.register("column/purpur_pillar_column2", () -> new BlockItem(BlocksRegistry.PURPUR_PILLAR_COLUMN2.get(), new Item.Properties().tab(ITEM_GROUP)));

	
	
	   public static final RegistryObject<BlockItem> CORNER = ITEMS.register("corner", () -> new BlockItem(BlocksRegistry.TOUCHSTONE_CORNER.get(), new Item.Properties().tab(ITEM_GROUP)));

	public static void registerItems(IEventBus bus) 
	{
		ITEMS.register(bus);
	}

}
